ipAddr: 39.105.35.4
server:
  port: 8000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${ipAddr}:3306/reserve_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    com.ty.order.dao: debug