server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
        # lb: 所有mall-product的请求都会被截取掉 /api/
        - id: room_route
          uri: lb://room
          predicates:
            - Path=/api/room/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: order_route
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
  application:
    name: gateway