ipAddr: 39.105.35.4
server:
  port: 7000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${ipAddr}:3306/reserve_room?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: room